### ISSUE TITLE
Make this available for VS 2022

### ISSUE THREAD

**Issue by koenbeuk** [ikkentim/vs-tye-explorer#1]
Looks super useful! My team is currently on VS2022 where this extension is not yet available.  Can we update this extension to VS2022 or is there anything blocking it? see: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

If you're unable due to lack of time, do you accept a PR? (I can probably take a swing at this over the weekend)

Thanks!

**Comment by ikkentim** [comment]
Thank you for your time and the PR! Please note I do aim to keep compatibility with VS2019 :) Please ping me when the PR is ready.

**Comment by koenbeuk** [comment]
@ikkentim The PR is ready. I've tested it on VS 2019 Enterprise and VS 2022 Professional (preview 3)
