### ISSUE TITLE
Care to release a new version of this extension?

### ISSUE THREAD

**Issue by koenbeuk** [ikkentim/vs-tye-explorer#5]
With the latest updates onboard? :)

**Comment by ikkentim** [comment]
Sure, here you go!

**Comment by ikkentim** [comment]
... It appears the marketplace doesn't yet show the extension to support VS2022. I'll have to look into that...

**Comment by ikkentim** [comment]
Due to a revert commit in #4 changes from #3 were reverted ¯\\_(ツ)_/¯

Fixed that, rebuild and reuploaded a new package to the marketplace, v0.4 is available now for VS2022
